import { Move } from "@/stats/item/class";

export const moves = {
  1: new Move({
    name: '',
    type: '',
    rollCount: 1,
    rollStat: '',
    targetText: '',
    damageAmpFloor: 0,
    damageAmpCeil: 0,
    splash: {
      applicable: false,
      damageAmpFloor: 0,
      damageAmpCeil: 0,
    },
    effects: [],
    tag: [],
    accuracyModifier: 0,
  }),

  areaBlast3: new Move({
    name: 'Area Blast',
    type: 'attack',
    rollCount: 3,
    rollStat: 'intelligence',
    targetText: 'Target Group',
    damageAmpCeil: 62,
    splash: {
      applicable: true,
      damageAmpFloor: 0,
      damageAmpCeil: 62,
    },
    tag: [ 'aoe' ],
    accuracyModifier: -5,
  }),
  armorUp1: new Move({
    name: 'Armor Up',
    type: 'buff',
    rollCount: 1,
    rollStat: 'vitality',
    targetText: 'Target Self',
    effects: [ 'Armor Up' ],
    tag: [ 'self' ],
  }),
  armorUpNeighbors1: new Move({
    name: 'Armor Up',
    type: 'buff',
    rollCount: 1,
    rollStat: 'vitality',
    targetText: 'Target Self',
    effects: [ 'Group Armor Up' ],
    tag: [ 'party' ],
  }),
  bash3: new Move({
    name: 'Bash',
    type: 'attack',
    rollCount: 3,
    rollStat: 'vitality',
    damageAmpFloor: 45,
    damageAmpCeil: 100,
    effects: [ 'Daze' ],
  }),
  bash4: new Move({
    name: 'Bash',
    type: 'attack',
    rollCount: 4,
    rollStat: 'vitality',
    damageAmpFloor: 45,
    damageAmpCeil: 100,
    effects: [ 'Daze' ],
  }),
  blast1: new Move({
    name: 'Blast',
    type: 'attack',
    rollCount: 1,
    rollStat: 'talent',
    targetText: 'Multiple Targets',
    damageAmpFloor: 0,
    damageAmpCeil: 100,
    splash: {
      applicable: true,
      damageAmpFloor: 0,
      damageAmpCeil: 50,
    },
    tag: [ 'aoe' ],
  }),
  blast3: new Move({
    name: 'Blast',
    type: 'attack',
    rollCount: 3,
    rollStat: 'intelligence',
    targetText: 'Single Target',
    damageAmpFloor: 49,
    damageAmpCeil: 100,
    splash: {
      applicable: true,
      damageAmpFloor: 24,
      damageAmpCeil: 50,
    },
    tag: [ 'splash' ],
  }),
  cure1: new Move({
    name: 'Cure',
    type: 'buff',
    rollCount: 1,
    rollStat: 'intelligence',
    targetText: 'Target Friendly',
    effects: [ 'Cure' ],
    tag: [ 'friendly' ],
  }),
  cut1: new Move({
    name: 'Cut',
    type: 'attack',
    rollCount: 1,
    rollStat: 'speed',
    targetText: 'Single Target',
    damageAmpFloor: 0,
    damageAmpCeil: 100,
    effects: [ 'Bleed' ],
    tag: [ 'single' ],
  }),
  darkBlast3: new Move({
    name: 'Dark Blast',
    type: 'attack',
    rollCount: 3,
    rollStat: 'intelligence',
    targetText: 'Single Target',
    damageAmpFloor: 45,
    damageAmpCeil: 100,
    splash: {
      applicable: true,
      damageAmpFloor: 24,
      damageAmpCeil: 50,
    },
    tag: [ 'splash' ],
  }),
  darkStorm3: new Move({
    name: 'Dark Storm',
    type: 'attack',
    rollCount: 3,
    rollStat: 'intelligence',
    targetText: 'Target Group',
    damageAmpCeil: 64,
    splash: {
      applicable: true,
      damageAmpFloor: 0,
      damageAmpCeil: 64,
    },
    tag: [ 'aoe' ],
  }),
  evadeUp1: new Move({
    name: 'Evade Up',
    type: 'buff',
    rollCount: 1,
    rollStat: 'speed',
    targetText: 'Target Self',
    effects: [ 'Evade Up' ],
    tag: [ 'self' ],
  }),
  explosiveShot1: new Move({
    name: 'Explosive Shot',
    type: 'attack',
    rollCount: 1,
    rollStat: 'strength',
    targetText: 'Single Target',
    damageAmpFloor: 0,
    damageAmpCeil: 100,
    splash: {
      applicable: true,
      damageAmpFloor: 0,
      damageAmpCeil: 50,
    },
    tag: [ 'splash' ],
  }),
  heavyDraw4: new Move({
    name: 'Heavy Draw',
    type: 'attack',
    rollCount: 4,
    rollStat: 'awareness',
    targetText: 'Single Target',
    damageAmpFloor: 0,
    damageAmpCeil: 154,
    tag: [ 'single' ],
    accuracyModifier: -20,
  }),
  ignite3: new Move({
    name: 'Ignite',
    type: 'attack',
    rollCount: 3,
    rollStat: 'vitality',
    targetText: 'Multiple Targets',
    splash: {
      applicable: true,
      damageAmpFloor: 0,
      damageAmpCeil: 0,
    },
    effects: [ 'Ignite' ],
    tag: [ 'line aoe' ],
  }),
  interrupt4: new Move({
    name: 'Interrupt',
    type: 'attack',
    rollCount: 4,
    rollStat: 'awareness',
    damageAmpCeil: 100,
    effects: [ 'Interrupt' ],
  }),
  fireBash3: new Move({
    name: 'Fire Bash',
    type: 'attack',
    rollCount: 3,
    rollStat: 'vitality',
    damageAmpFloor: 36,
    damageAmpCeil: 100,
    effects: [ 'Ignite' ],
  }),
  frostBash: new Move({
    name: 'Frost Bash',
    type: 'attack',
    rollCount: 4,
    rollStat: 'vitality',
    damageAmpCeil: 100,
    effects: [ 'Freeze', 'Daze' ],
  }),
  ray4: new Move({
    name: 'Ray',
    type: 'attack',
    rollCount: 4,
    rollStat: 'intelligence',
    targetText: 'Single Target',
    damageAmpFloor: 49,
    damageAmpCeil: 100,
    tag: [ 'single' ],
    accuracyModifier: 0,
  }),
  resistUp1: new Move({
    name: 'Resist Up',
    type: 'buff',
    rollCount: 1,
    rollStat: 'vitality',
    targetText: 'Target Self',
    effects: [ 'Resist Up' ],
    tag: [ 'self' ],
  }),
  rowAttack2: new Move({
    name: 'Row Attack',
    type: 'attack',
    rollCount: 2,
    rollStat: 'talent',
    targetText: 'Multiple Targets',
    damageAmpFloor: 0,
    damageAmpCeil: 70,
    splash: {
      applicable: true,
      damageAmpFloor: 0,
      damageAmpCeil: 70,
    },
    tag: [ 'row' ],
  }),
  pierce2: new Move({
    name: 'Pierce',
    type: 'attack',
    rollCount: 2,
    rollStat: 'awareness',
    damageAmpFloor: 0,
    damageAmpCeil: 100,
    effects: [ 'Ignore Armor' ],
    accuracyModifier: -5,
  }),
  pistolWhip1: new Move({
    name: 'Pistol Whip',
    type: 'attack',
    rollCount: 1,
    rollStat: 'talent',
    targetText: 'Single Target',
    damageAmpFloor: 0,
    damageAmpCeil: 25,
    effects: [ 'Daze' ],
    tag: [ 'single' ],
  }),
  protectSelf1: new Move({
    name: 'Protect Self',
    type: 'buff',
    rollCount: 1,
    rollStat: 'vitality',
    targetText: 'Target Self',
    effects: [ 'Protect' ],
    tag: [ 'self' ],
  }),
  push4: new Move({
    name: 'Push',
    type: 'attack',
    rollCount: 4,
    rollStat: 'awareness',
    damageAmpCeil: 100,
    effects: [ 'Daze' ],
  }),
  slash2: new Move({
    name: 'Slash',
    type: 'attack',
    rollCount: 2,
    rollStat: 'speed',
    damageAmpFloor: 49,
    damageAmpCeil: 100,
  }),
  shank1: new Move({
    name: 'Shank',
    type: 'attack',
    rollCount: 1,
    rollStat: 'speed',
    targetText: 'Single Target',
    damageAmpFloor: 0,
    damageAmpCeil: 100,
    effects: [ 'Ignore Armor' ],
    tag: [ 'single' ],
  }),
  shatter1: new Move({
    name: 'Shatter',
    type: 'attack',
    rollCount: 1,
    rollStat: 'strength',
    damageAmpCeil: 100,
    effects: [ 'Bleed' ],
  }),
  shockArrow1: new Move({
    name: 'Shock Arrow',
    type: 'attack',
    rollCount: 1,
    rollStat: 'awareness',
    targetText: 'Single Target',
    damageAmpFloor: 0,
    damageAmpCeil: 100,
    effects: [ 'Shock' ],
    tag: [ 'single' ],
  }),
  shockRecoil1: new Move({
    name: 'Shock Recoil',
    type: 'attack',
    rollCount: 1,
    rollStat: 'awareness',
    targetText: 'Single Target',
    damageAmpFloor: 0,
    damageAmpCeil: 50,
    effects: [ 'Shock', 'Daze' ],
    tag: [ 'single' ],
  }),
  shockStrike2: new Move({
    name: 'Shock Strike',
    type: 'attack',
    rollCount: 2,
    rollStat: 'speed',
    damageAmpCeil: 100,
    effects: [ 'Shock' ]
  }),
  shot2: new Move({
    name: 'Shot',
    type: 'attack',
    rollCount: 2,
    rollStat: 'awareness',
    damageAmpFloor: 45,
    damageAmpCeil: 100,
  }),
  shot4: new Move({
    name: 'Shot',
    type: 'attack',
    rollCount: 4,
    rollStat: 'awareness',
    damageAmpFloor: 45,
    damageAmpCeil: 100,
  }),
  stab2: new Move({
    name: 'Stab',
    type: 'attack',
    rollCount: 2,
    rollStat: 'speed',
    damageAmpCeil: 100,
    effects: [ 'Ignore Armor' ],
    accuracyModifier: -5,
  }),
  stun2: new Move({
    name: 'Stun',
    type: 'attack',
    rollCount: 2,
    rollStat: 'vitality',
    effects: [ 'Stun' ],
  }),
  stun3: new Move({
    name: 'Stun',
    type: 'attack',
    rollCount: 3,
    rollStat: 'vitality',
    effects: [ 'Stun' ],
  }),
  stun4: new Move({
    name: 'Stun',
    type: 'attack',
    rollCount: 4,
    rollStat: 'vitality',
    effects: [ 'Stun' ],
  }),
  tauntSpeed2: new Move({
    name: 'Taunt',
    type: 'buff',
    rollCount: 2,
    rollStat: 'speed',
    targetText: 'Target Self',
    effects: [ 'Taunt' ],
    tag: [ 'self' ],
  }),
  tauntVitality2: new Move({
    name: 'Taunt',
    type: 'buff',
    rollCount: 2,
    rollStat: 'vitality',
    targetText: 'Target Self',
    effects: [ 'Taunt' ],
    tag: [ 'self' ],
  }),
  throw2: new Move({
    name: 'Throw',
    type: 'attack',
    rollCount: 2,
    rollStat: 'talent',
    targetText: 'Single Target',
    damageAmpFloor: 49,
    damageAmpCeil: 100,
    effects: [ 'Daze' ],
    tag: [ 'single' ],
    accuracyModifier: 0,
  }),


  armorSmash3: new Move({
    name: 'Armor Smash',
    type: 'attack',
    rollCount: 3,
    rollStat: 'strength',
    targetText: 'Single Target',
    damageAmpFloor: 0,
    damageAmpCeil: 120,
    effects: [ 'Armor Down' ],
    tag: [ 'single' ],
    accuracyModifier: -15,
  }),
  bash2: new Move({
    name: 'Bash',
    type: 'attack',
    rollCount: 2,
    rollStat: 'vitality',
    damageAmpFloor: 35,
    damageAmpCeil: 100,
    effects: [ 'Daze' ],
  }),
  bash5: new Move({
    name: 'Bash',
    type: 'attack',
    rollCount: 5,
    rollStat: 'vitality',
    damageAmpFloor: 28,
    damageAmpCeil: 100,
    effects: [ 'Daze' ],
  }),
  bashTH5: new Move({
    name: 'Bash',
    type: 'attack',
    rollCount: 5,
    rollStat: 'awareness',
    targetText: 'Single Target',
    damageAmpFloor: 0,
    damageAmpCeil: 140,
    tag: [ 'single' ],
    accuracyModifier: -15,
  }),
  chop3: new Move({
    name: 'Chop',
    type: 'attack',
    rollCount: 3,
    rollStat: 'strength',
    targetText: 'Single Target',
    damageAmpFloor: 40,
    damageAmpCeil: 100,
    tag: [ 'single' ],
  }),
  chop5: new Move({
    name: 'Chop',
    type: 'attack',
    rollCount: 5,
    rollStat: 'strength',
    targetText: 'Single Target',
    damageAmpFloor: 45,
    damageAmpCeil: 100,
    tag: [ 'single' ],
  }),
  cuttingSlice3: new Move({
    name: 'Cutting Slice',
    type: 'attack',
    rollCount: 3,
    rollStat: 'strength',
    damageAmpFloor: 0,
    damageAmpCeil: 100,
    effects: [ 'Bleed' ],
    tag: [ 'single' ],
    accuracyModifier: -5,
  }),
  heavyBash5: new Move({
    name: 'Heavy Bash',
    type: 'attack',
    rollCount: 5,
    rollStat: 'vitality',
    targetText: 'Single Target',
    damageAmpFloor: 0,
    damageAmpCeil: 150,
    effects: [ 'Daze' ],
    tag: [ 'single' ],
    accuracyModifier: -20,
  }),
  heavyStrike4: new Move({
    name: 'Heavy Strike',
    type: 'attack',
    rollCount: 4,
    rollStat: 'strength',
    damageAmpFloor: 0,
    damageAmpCeil: 150,
    accuracyModifier: -20,
  }),
  heavyCut5: new Move({
    name: 'Heavy Cut',
    type: 'attack',
    rollCount: 5,
    rollStat: 'strength',
    targetText: 'Single Target',
    damageAmpFloor: 0,
    damageAmpCeil: 130,
    effects: [ 'Bleed' ],
    tag: [ 'single' ],
    accuracyModifier: -15,
  }),
  heavyShockBolt5: new Move({
    name: 'Heavy Shock Bolt',
    type: 'attack',
    rollCount: 5,
    rollStat: 'intelligence',
    targetText: 'Single Target',
    damageAmpFloor: 0,
    damageAmpCeil: 154,
    effects: [ 'Shock' ],
    tag: [ 'single' ],
    accuracyModifier: -20,
  }),
  pull2: new Move({
    name: 'Pull',
    type: 'attack',
    rollCount: 2,
    rollStat: 'intelligence',
    targetText: 'Single Target',
    damageAmpFloor: 0,
    damageAmpCeil: 100,
    effects: [ 'Daze' ],
    tag: [ 'single' ],
  }),
  slash3: new Move({
    name: 'Slash',
    type: 'attack',
    rollCount: 3,
    rollStat: 'strength',
    damageAmpFloor: 36,
    damageAmpCeil: 100,
  }),
  slash4: new Move({
    name: 'Slash',
    type: 'attack',
    rollCount: 4,
    rollStat: 'strength',
    damageAmpFloor: 35,
    damageAmpCeil: 100,
  }),
  shockStrike3: new Move({
    name: 'Shock Strike',
    type: 'attack',
    rollCount: 3,
    rollStat: 'vitality',
    targetText: 'Single Target',
    damageAmpCeil: 100,
    effects: [ 'Shock' ],
    tag: [ 'single' ],
  }),
  shockBolt4: new Move({
    name: 'Shock Bolt',
    type: 'attack',
    rollCount: 4,
    rollStat: 'intelligence',
    targetText: 'Single Target',
    damageAmpFloor: 0,
    damageAmpCeil: 100,
    effects: [ 'Shock' ],
    tag: [ 'single' ],
  }),
  shot3: new Move({
    name: 'Shot',
    type: 'attack',
    rollCount: 3,
    rollStat: 'awareness',
    damageAmpFloor: 45,
    damageAmpCeil: 100,
  }),
  thrust5: new Move({
    name: 'Thrust',
    type: 'attack',
    rollCount: 5,
    rollStat: 'awareness',
    targetText: 'Multiple Targets',
    damageAmpFloor: 0,
    damageAmpCeil: 100,
    splash: {
      applicable: true,
      damageAmpFloor: 0,
      damageAmpCeil: 0,
    },
    tag: [ 'aoe' ],
    accuracyModifier: 0,
  }),
  volley3: new Move({
    name: 'Volley',
    type: 'attack',
    rollCount: 3,
    rollStat: 'awareness',
    targetText: 'Target Group',
    damageAmpFloor: 0,
    damageAmpCeil: 45,
    splash: {
      applicable: true,
      damageAmpFloor: 0,
      damageAmpCeil: 45,
    },
    effects: [ 'Ignore Armor' ],
    tag: [ 'aoe' ],
  }),
  waterBolt4: new Move({
    name: 'Water Bolt',
    type: 'attack',
    rollCount: 4,
    rollStat: 'intelligence',
    damageAmpCeil: 100,
    splash: {
      applicable: false,
      damageAmpFloor: 0,
      damageAmpCeil: 0,
    },
    effects: [ 'Wet' ],
  }),
  zap2: new Move({
    name: 'Zap',
    type: 'attack',
    rollCount: 2,
    rollStat: 'intelligence',
    targetText: 'Single Target',
    damageAmpFloor: 25,
    damageAmpCeil: 100,
    effects: [ 'Ignore Armor' ],
    tag: [ 'single' ],
  }),

}